# Generated by Django 4.2 on 2023-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heraxos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Heraxos name')),
                ('price', models.PositiveIntegerField(verbose_name='Heraxos price')),
                ('img', models.ImageField(upload_to='Heraxos image', verbose_name='Heraxos image')),
            ],
        ),
    ]
